import { guide } from './types';
export const businessGuides = [
  guide('business', {
    id: 'leads',
    title: 'Manage leads and opportunities',
    summary: 'Keep the person in Contacts and each potential job in its own opportunity.',
    when: 'A prospect asks about a new project.',
    destination: 'leads',
    updated: '2026-09-30',
    steps: [
      'Add or find the client/prospect in Contacts.',
      'Open Leads. A CRM administrator defines company stages and sources under Stages & sources.',
      'Choose New opportunity. Enter the potential job, existing contact, owner, stage, property details, source and estimated value.',
      'Use Pipeline or List, search and status filters. Open the opportunity to move its stage or record Won/Lost. Lost requires a reason.',
      'Record the next follow-up and add an activity with an owner, due date and notes. Mark completed activities complete.',
    ],
    next: 'Open follow-ups appear in Dashboard/My Work for authorized staff. Values and probabilities are sales estimates, never booked revenue.',
    notes: [
      'CRM administrators see the company pipeline; other CRM users see opportunities they own. Company/contact changes do not grant portal access.',
    ],
    related: ['lead-conversion', 'sales-follow-ups'],
  }),
  guide('business', {
    id: 'lead-conversion',
    title: 'Convert a won opportunity to a project',
    summary: 'Use the normal project wizard without duplicating the client.',
    when: 'The opportunity is won and ready for project setup.',
    destination: 'leads',
    steps: [
      'Save the opportunity as Won.',
      'Reopen it and choose Convert to project.',
      'Review the prefilled contact, project title, property details and manager. Enter a unique project number.',
      'Choose dates, team and a company template or selective source-project structure.',
      'Create the project. The opportunity retains a link to it.',
    ],
    next: 'Template records copy through the existing setup transaction. Repeated conversion cannot create a second project.',
    notes: [
      'Internal sales notes, messages, approvals, actuals and accounting records are not copied. A prospect contact becomes a client as part of successful conversion.',
    ],
    related: ['create-project', 'leads'],
  }),
  guide('business', {
    id: 'sales-follow-ups',
    title: 'Record sales calls and follow-ups',
    summary: 'Assign the next sales action to a person and due date.',
    when: 'After a call, consultation or proposal discussion.',
    destination: 'leads',
    steps: [
      'Open the opportunity.',
      'Use Activities & follow-ups to enter the next action, owner, due date and communication notes.',
      'Save the follow-up.',
      'Return to complete it after the action is finished.',
    ],
    next: 'Open work appears in authorized work queues. Enabled scheduled reminders can notify the owner.',
    notes: [
      'This records communication notes; it does not connect a mailbox or automatically send sales emails.',
    ],
    related: ['leads', 'reminders'],
  }),
  guide('business', {
    id: 'warranty',
    title: 'Manage warranty and service requests',
    summary: 'Review reported issues, assign repairs and retain completion evidence.',
    when: 'A client reports a service issue, or staff records one for them.',
    destination: 'projects',
    steps: [
      'Open Project → Warranty. Create a request or open a client submission.',
      'Review, then Accept or Reject with a reason. Rejection means Not warranty; it does not delete the request.',
      'Assign project staff or an existing project trade. Enter a trade-safe scope and due date.',
      'Schedule an appointment if needed. Appointment dates are visible to the reporting client and assigned trade.',
      'The trade can acknowledge, start, upload completion evidence and mark Ready for review.',
      'Cedar Winds checks the work and marks Complete, which means Ready for client.',
      'The reporting client verifies it; staff then closes it. Reopen with a reason if further work is needed.',
    ],
    next: 'Status history and files remain as evidence. No warranty action creates costs or changes a commitment.',
    notes: [
      'Client comments/files and trade comments/files are separate audiences. Use the upload visibility selector deliberately. Changing the assigned trade after evidence is shared requires a replacement request. Warranty dates are manually entered operational dates, not legal coverage rules.',
    ],
    related: ['warranty-client', 'warranty-trade', 'reminders'],
  }),
  guide('business', {
    id: 'warranty-client',
    title: 'Help a client report and verify service work',
    summary: 'Clients use Warranty in their own portal; staff can check it through Client Vision.',
    when: 'Helping a client with a reported issue.',
    destination: 'projects',
    steps: [
      'Confirm explicit client project access is active.',
      'The client opens Warranty and submits the title, description and location, then attaches photos or PDF evidence.',
      'Staff reviews and handles the request from the project Warranty workspace.',
      'Once staff marks work complete, the reporting client uses Verify.',
      'Use the eye icon and select that client to preview the same request. Preview controls cannot submit or approve.',
    ],
    next: 'Requests belong to the reporting client identity. Other project clients do not receive private request details.',
    related: ['client-vision', 'warranty'],
  }),
  guide('business', {
    id: 'warranty-trade',
    title: 'Assign warranty work to a trade',
    summary: 'Share only the assigned service scope and trade-classified evidence.',
    when: 'A subcontractor needs to perform service work.',
    destination: 'projects',
    steps: [
      'Accept the request, then select the existing project trade and enter trade-safe instructions.',
      'Ensure the trade has active portal access. Assignment alone does not grant access.',
      'The trade opens Warranty to acknowledge, start or mark Ready for review.',
      'Review their completion photos and comments before completing the work for the client.',
    ],
    next: 'Trades cannot decide warranty coverage, see client-private comments or close their own request.',
    related: ['warranty', 'trade-access'],
  }),
  guide('business', {
    id: 'business-reports',
    title: 'Run and save business reports',
    summary:
      'Review accessible projects, tasks, financials, sales, time, purchasing, decisions, trades, activity and warranty.',
    when: 'Preparing a weekly review or investigating outstanding work.',
    destination: 'reports',
    steps: [
      'Open Reports and select a report you have permission to use.',
      'Choose project, search text, status and applicable Due/date filters. Financial reports are cumulative, not accounting period statements.',
      'Choose Run report, then sort a column or open the underlying record.',
      'Export CSV or Print report after checking the results.',
      'Name the view and choose Save view to reuse its filters. Saved views rerun authorization; they do not freeze or share data.',
    ],
    next: 'Reports show operational records. Financial amounts come from existing normalized job costing, with margin shown only to authorized users.',
    notes: [
      'No payroll/overtime calculations, general ledger statements or free-form report designer are provided. CSV exports contain the current result set.',
    ],
    related: ['job-cost', 'reminders'],
  }),
  guide('business', {
    id: 'reminders',
    title: 'Enable reminders, daily digests and weekly reviews',
    summary:
      'Optional scheduled notifications help people find due work without changing project or accounting records.',
    when: 'An administrator has configured the scheduled worker.',
    destination: 'my-work',
    steps: [
      'In Settings, authorized administrators enable scheduled reminders and separately enable email if desired.',
      'In My Work, opt in to your own daily work digest.',
      'In Project → Warranty, enter warranty dates and optionally enable a weekly client project review.',
      'Review recent runs and delivery exceptions in Settings.',
      'Open the secure link in a notification to review the latest authorized details.',
    ],
    next: 'The worker creates deduplicated inbox notifications for due selections, tasks, trades, warranty, sales follow-ups and QuickBooks health. Summaries contain safe counts and secure links.',
    notes: [
      'Normal reminders require an external cron, company enablement and the configured production rollout stage. The separate internal readiness test does not enable normal reminders. In-app notifications are authoritative. An uncertain SMTP delivery requires review; it is not automatically resent. No message content, internal pricing or legal warranty rules are inferred.',
    ],
    related: ['notifications', 'business-reports'],
  }),
  guide('business', {
    id: 'production-readiness',
    title: 'Check production readiness',
    summary:
      'Test storage, your email delivery and one harmless internal reminder before company rollout.',
    when: 'An Owner or Controller is preparing or checking the live service.',
    destination: 'admin',
    roles: ['OWNER', 'CONTROLLER'],
    updated: '2026-09-29',
    steps: [
      'Open Settings and find Production readiness. Configuration alone is not proof of a successful live test.',
      'After your administrator configures private object storage, run Test private storage and access. It creates temporary diagnostic identities and small files, checks access rules and removes the file bytes. Archived test records remain for audit.',
      'Choose Send my test email once. Check your inbox and confirm receipt. If the result is uncertain, check the provider before sending again.',
      'Run the internal scheduler test twice. The first creates one inbox notification; the second must create zero. Neither sends email or enables reminders.',
      'Ask the administrator to configure the protected external scheduler. Roll reminders out gradually; company enablement and deployment rollout stage must both permit delivery.',
    ],
    next: 'Successful tests are recorded with the current configuration. Changes to storage or email configuration require a new test. QuickBooks live validation remains separate.',
    notes: [
      'Storage failures or interrupted tests require cleanup review. Keep financial and approval evidence; do not delete the database to clean up tests.',
      'The in-app scheduler test proves durable execution, not that an external cron is running. SMTP submission is not proof of inbox delivery.',
    ],
    related: ['reminders'],
  }),
];
