import { guide } from './types';
export const financialGuides = [
  guide('estimating', {
    id: 'create-estimate',
    title: 'Creating an Estimate',
    summary:
      'Build the project’s internal expected cost and client selling price together without confusing them.',
    when: 'Preparing a quote or a new pricing revision.',
    destination: 'projects',
    related: [
      'estimate-templates',
      'catalog-quick-add',
      'assemblies',
      'estimate-pricing',
      'create-proposal',
    ],
    keywords: ['estimate', 'estimating', 'quote'],
    steps: [
      'Open Project → Estimate and create an estimate with a meaningful title. Choose its current editable revision.',
      'Use template, Add from Cost Catalog or Add assembly to bring in repeatable work; use the custom line action for something new.',
      'Organize lines into sections. Enter description, Cost Code, Cost Type, quantity, unit, unit cost and markup.',
      'Set client description, taxable, optional and allowance flags deliberately in the line editor.',
      'Review the server-calculated totals. Save inline changes explicitly; refresh if someone else changed the revision.',
    ],
    next: 'Create a proposal from the reviewed estimate revision when ready to present client pricing.',
    notes: [
      'Sections organize the estimate; Cost Codes and Cost Types determine financial reporting. A reusable time-clock Task is not an estimate line or schedule task.',
    ],
  }),
  guide('estimating', {
    id: 'estimate-pricing',
    title: 'Quantity, cost, markup, client price and HST',
    summary: 'Understand how a line becomes an internal cost and a client price.',
    when: 'Entering or checking estimate and Change Order pricing.',
    destination: 'projects',
    related: ['create-estimate', 'estimate-flags', 'job-cost'],
    steps: [
      'Quantity × unit cost gives the line cost, rounded to cents. Use a unit label that matches the measurement, such as hours, each or SF.',
      'Choose NONE for no markup, FIXED for a fixed amount on the line, or PERCENT_ON_COST for a percentage of line cost.',
      'Review client price: line cost plus markup. The server calculates it; it is not a separate unverified number.',
      'Mark taxable lines appropriately and check the configured HST/tax rate and totals before presenting a proposal.',
    ],
    next: 'Client output uses selling prices and tax; internal costing stays in authorized workspaces.',
    extra: [
      {
        heading: 'Markup is not margin',
        paragraphs: [
          'A $100 cost with 25% markup sells for $125. Profit is $25 and margin is 20% ($25 ÷ $125), not 25%. Fixed markup is a dollar amount for the line, not a percentage.',
        ],
        kind: 'financial',
      },
      {
        heading: 'Cost Types',
        paragraphs: [
          'LABOUR is labour cost; MATERIAL is purchased materials; SUBCONTRACT is trade/subcontract scope; EQUIPMENT is equipment cost; OTHER is other classified project cost. Choose the intended classification rather than using a presentation section as a substitute.',
        ],
      },
    ],
    notes: [
      'Profit and margin require separate permission. HST is not profit and is excluded from internal cost-budget/contract revenue reporting.',
    ],
  }),
  guide('estimating', {
    id: 'estimate-flags',
    title: 'Optional items, allowances and client wording',
    summary: 'Label the meaning of a line before it becomes part of a proposal.',
    when: 'Pricing choices, included allowances or different internal/client descriptions.',
    destination: 'projects',
    related: ['estimate-allowances', 'create-proposal', 'estimate-revisions'],
    steps: [
      'Use the custom line editor to review Included, Optional, Allowance and Taxable flags.',
      'Keep internal estimating detail in the internal description/notes and write a clear client description for the proposal.',
      'Check which lines are included in the calculated total and proposal preview; Included controls whether a line enters totals and the proposal/budget. Optional is a separate label and does not by itself remove a line from the total.',
      'For an included allowance, confirm its contractual selling value rather than treating supplier cost as the client allowance.',
    ],
    next: 'Accepted allowance lines can later create source-linked project allowances and selections.',
    notes: [
      'Do not use an optional price as an accepted budget baseline without including it in the approved pricing. Preview the document before issue.',
    ],
  }),
  guide('estimating', {
    id: 'estimate-revisions',
    title: 'Estimate revisions and locked pricing',
    summary: 'Preserve the pricing that supported an offer instead of overwriting it.',
    when: 'Changing an estimate after a proposal snapshot has been created.',
    destination: 'projects',
    related: ['proposal-revisions', 'create-estimate'],
    steps: [
      'Open the estimate and inspect its revision/status. Draft or internal-review pricing can be edited.',
      'If it is locked, create a new revision using the revision action.',
      'Review the copied lines, change the new revision and save.',
      'Create a new proposal from the correct revised estimate when a changed client offer is required; the proposal New revision action currently copies the existing snapshot.',
    ],
    next: 'Earlier pricing remains available for historical comparison and the accepted budget source.',
    notes: [
      'Creating a proposal snapshot already locks its source estimate as Ready. Do not assume an unissued proposal means its source estimate is still editable.',
    ],
    kind: 'locked',
  }),
  guide('proposals', {
    id: 'create-proposal',
    title: 'Creating and issuing a Proposal',
    summary: 'Present a stable client-facing offer from a reviewed estimate.',
    when: 'The estimate is ready for client review.',
    destination: 'projects',
    related: ['create-estimate', 'proposal-templates', 'accept-proposal', 'proposal-revisions'],
    steps: [
      'Open Project → Proposals and create a proposal from the correct estimate revision and client.',
      'Populate introduction, scope, exclusions, assumptions and terms using reviewed wording where available.',
      'Create the proposal, open its preview and check names, addresses, line descriptions, client prices, tax and total.',
      'Use Print / Save as PDF for a printable copy.',
      'Issue the proposal when authorized and deliver it through your agreed client communication process.',
    ],
    next: 'The source estimate and document snapshot preserve the offered pricing and wording.',
    notes: [
      'The proposal output excludes internal cost, markup and margin. Issue records a document state; it does not by itself prove delivery or provide a regulated digital signature.',
    ],
    kind: 'client',
  }),
  guide('proposals', {
    id: 'accept-proposal',
    title: 'Accept a Proposal and create the Budget',
    summary: 'Record the client’s acceptance and establish the internal expected-cost baseline.',
    when: 'An issued proposal has been accepted by the client.',
    destination: 'projects',
    related: ['job-cost', 'proposal-revisions', 'change-approval'],
    steps: [
      'Open the issued proposal and verify it is the revision the client accepted.',
      'Use Mark accepted only after confirming the client’s acceptance. The current action records the signed-in staff member and timestamp; retain the client’s evidence in the project record.',
      'Create the budget from the accepted proposal using the available budget action; if already created, open the existing budget instead.',
      'Open Budget to confirm Original and Current cost allocations. Confirm the original contract amount separately in Project settings.',
    ],
    next: 'The budget uses included estimate cost, not the client selling price. Duplicate budget creation is blocked.',
    notes: [
      'Only an issued proposal can be accepted. Original/Current budget creation does not authorize purchasing or invite clients. Proposal acceptance is recorded internally in the current implementation.',
    ],
  }),
  guide('proposals', {
    id: 'proposal-revisions',
    title: 'Revising a Proposal without losing history',
    summary: 'Create a new offer while preserving what was previously issued.',
    when: 'Client wording or pricing changes before the final accepted scope.',
    destination: 'projects',
    related: ['estimate-revisions', 'create-proposal', 'change-orders'],
    steps: [
      'Review the existing proposal’s revision and status.',
      'For changed pricing, create and edit a new estimate revision first.',
      'New revision currently copies the existing snapshot and source estimate; it does not offer a draft wording/pricing editor. For changed pricing or wording, create a new proposal from the corrected estimate and text, and clearly identify which offer replaces the old one.',
      'Keep the accepted contract intact; use Change Orders for later contractual changes.',
    ],
    next: 'Historical issued documents retain their own identities, prices and wording.',
    notes: [
      'Changing a contact, company setting or project address later does not rewrite an old snapshot.',
    ],
    kind: 'locked',
  }),
  guide('budget', {
    id: 'job-cost',
    title: 'Reading Budget, Committed, Actual, Forecast and Variance',
    summary:
      'See the internal cost baseline, remaining obligations and expected finish by Cost Code and Cost Type.',
    when: 'Reviewing project financial health or checking a newly reconciled invoice.',
    destination: 'projects',
    related: ['commitment-fulfillment', 'contract-summary', 'actual-costs'],
    steps: [
      'Open Project → Budget and confirm the Original and Current budget versions.',
      'Read each Cost Code/Cost Type row rather than comparing unlike categories.',
      'Investigate remaining commitments and actual costs together; open purchasing/reconciliation records where needed.',
      'Review negative variance and the underlying costs before making decisions.',
    ],
    next: 'Accepted Change Orders, issued purchasing and reconciled actuals flow through this report.',
    extra: [
      {
        heading: 'What the columns mean',
        paragraphs: [
          'Original Budget: included internal expected cost from the accepted baseline. Current Budget: the latest approved cost snapshot, including accepted changes.',
          'Committed: remaining committed amount after consumption, not the full historical PO total. Actual: incurred costs recorded in the normalized project ledger.',
          'Forecast: the greater of Current Budget and Actual + Remaining Committed + Forecast Adjustment. Variance: Current Budget minus Forecast. Negative means overrun; this forecast floor normally prevents a positive savings variance.',
        ],
        kind: 'financial',
      },
    ],
    notes: [
      'Time hours do not automatically become wage costs: employee costing rates/payroll calculations are not implemented.',
    ],
  }),
  guide('budget', {
    id: 'contract-summary',
    title: 'Original contract, approved changes and forecast profit',
    summary: 'Separate client revenue from the internal cost budget.',
    when: 'Reviewing the contract position or expected project return.',
    destination: 'projects',
    related: ['job-cost', 'change-approval'],
    steps: [
      'Read Original Contract as the preserved project baseline.',
      'Read Approved Change Orders as accepted pre-tax client adjustments. Current Contract is the original plus those adjustments.',
      'Compare Current Contract with Forecast final cost. Forecast Profit is their difference; Forecast Margin divides that profit by Current Contract.',
      'Use budget history to trace cost changes separately from selling-price changes.',
    ],
    next: 'Future accepted changes create new adjustments and budget snapshots; they do not erase the original baseline.',
    notes: [
      'Profit/margin require permission. Tax is excluded. A $20,000 internal-cost change sold for $27,000 increases the budget by $20,000 and contract by $27,000, not by the same amount.',
    ],
    kind: 'financial',
  }),
  guide('budget', {
    id: 'actual-costs',
    title: 'Manual Actual Costs, linking and reversal',
    summary: 'Record authorized project costs and reconcile their connection to purchasing.',
    when: 'Recording a manual cost or correcting an incorrect commitment link.',
    destination: 'projects',
    related: ['commitment-fulfillment', 'qb-bills', 'qb-reconciliation'],
    steps: [
      'Use Budget’s manual actual entry or the purchasing commitment/actual register, according to your permissions.',
      'Choose the correct project Cost Code, Cost Type, amount and date. Link the matching CommitmentLine when the cost fulfills issued work.',
      'For an unlinked manual actual, use Reconcile to allocate it to the correct remaining commitment.',
      'For an incorrect manual cost, use the authorized reversal action with a reason instead of deleting it.',
    ],
    next: 'Linking consumes commitment and updates fulfillment atomically. Reversal restores the consumed amount where the commitment remains active.',
    notes: [
      'QuickBooks-derived actuals must use QuickBooks reconciliation/hold controls, not generic manual reversal. Overages are rejected; revise the purchasing commitment first.',
    ],
  }),
  guide('purchasing', {
    id: 'purchase-orders',
    title: 'Creating, approving and issuing a Purchase Order',
    summary: 'Document a supplier purchase and turn issued costs into a project commitment.',
    when: 'Ordering materials or other vendor-supplied work.',
    destination: 'projects',
    related: ['work-orders', 'purchasing-revisions', 'commitment-fulfillment', 'qb-po'],
    steps: [
      'Open Project → Purchase Orders and create a Purchase Order draft. Select the vendor contact and appropriate billing contact.',
      'Enter title, scope, expected date, terms and vendor-facing notes. Add classified lines with quantity, unit and unit cost; no client markup applies.',
      'Review attachments and any related schedule task or Change Order. Keep internal notes private.',
      'Submit for internal review, obtain approval and then issue using the authorized actions.',
      'Preview/print the issued document and confirm the recipient receives it through the intended channel.',
    ],
    next: 'Only issuance establishes commitment. The correct invited trade contact can view and acknowledge its issued document.',
    notes: [
      'Draft, Internal review and Approved are not financially committed. Issue is not proof of delivery. Vendor acknowledgement is receipt evidence, not fulfillment.',
    ],
    kind: 'financial',
  }),
  guide('purchasing', {
    id: 'work-orders',
    title: 'Work Orders / Subcontracts and standard scope',
    summary: 'Use a Work Order for a trade’s defined scope; use a PO for a supplier purchase.',
    when: 'Engaging excavation, electrical, cabinetry or another subcontract scope.',
    destination: 'projects',
    related: ['scope-templates', 'trade-access', 'purchasing-revisions'],
    steps: [
      'Create a document in Project → Purchase Orders and choose Work Order. Select the actual subcontractor contact.',
      'Use a Scope Template, then adapt scope and terms to the project.',
      'Enter cost-code allocations and agreed trade values. Link a schedule task and suitable drawings/files where available.',
      'Review, approve and issue through the same controlled purchasing lifecycle.',
      'Grant trade portal access separately and follow up on acknowledgement of the current revision.',
    ],
    next: 'Issued Work Orders feed the same commitment ledger as POs.',
    notes: [
      'Work Orders currently remain CWManagement-only; they are not exported as QuickBooks POs. Acknowledgement does not change the agreed price or authorize extra work.',
    ],
  }),
  guide('purchasing', {
    id: 'purchasing-revisions',
    title: 'Purchasing revisions, cancellation and acknowledgement',
    summary: 'Change a commitment without erasing issued scope or breaking invoice links.',
    when: 'An approved/issued PO or Work Order needs correction or cancellation.',
    destination: 'projects',
    related: ['purchase-orders', 'commitment-fulfillment', 'trade-access'],
    steps: [
      'Create a new revision rather than editing an issued document. Review and approve its revised lines.',
      'Issue the replacement when ready. The old issued commitment stays effective until replacement issuance.',
      'Ask the recipient to acknowledge the new revision; its receipt is separate from the prior one.',
      'To cancel, use the authorized cancellation action and provide the reason after reviewing existing actual costs.',
    ],
    next: 'Old snapshots and receipts remain. Cancellation removes remaining exposure but preserves incurred actuals.',
    notes: [
      'You cannot reduce a line below consumed cost, remove a consumed line or change its ledger classification. Vendor changes after first issue require cancellation and a new family. A synchronized QuickBooks PO also needs accounting-side review.',
    ],
    kind: 'locked',
  }),
  guide('purchasing', {
    id: 'commitment-fulfillment',
    title: 'Partial fulfillment and avoiding double-counted cost',
    summary: 'A linked actual uses up part of a commitment rather than adding the same cost twice.',
    when: 'A vendor invoice or imported Bill fulfills a PO/Work Order.',
    destination: 'projects',
    related: ['actual-costs', 'qb-bills', 'job-cost'],
    steps: [
      'Find the issued commitment and the correct project/classification line.',
      'Record or reconcile the actual against that line using the authorized workflow.',
      'Check Partially fulfilled or Fulfilled status and the remaining amount.',
      'If the invoice exceeds what remains, obtain an approved/issued purchasing revision before retrying.',
    ],
    next: 'The report combines remaining commitments and actuals, and full consumption leaves zero remaining.',
    extra: [
      {
        heading: 'Example',
        paragraphs: [
          'PO $10,000; linked Bill $4,000: remaining commitment $6,000 plus actual $4,000 equals $10,000 exposure. An unlinked Bill does not automatically consume a PO merely because its amount or vendor looks similar.',
        ],
        kind: 'financial',
      },
    ],
    notes: [
      'Acknowledging a document is not financial fulfillment. There is no silent overconsumption override.',
    ],
  }),
  guide('changes', {
    id: 'change-orders',
    title: 'Creating and issuing a Change Order',
    summary: 'Document a client-facing contract change separately from a vendor purchase.',
    when: 'Scope, price or agreed schedule impact changes.',
    destination: 'projects',
    related: ['change-approval', 'change-revisions', 'selection-decisions'],
    keywords: ['change order', 'CO', 'credit'],
    steps: [
      'Open Project → Change Orders and create a draft with title, reason/category and client-visible scope.',
      'Enter internal expected costs and markup to calculate client prices. Check HST, terms, attachments and whole-day schedule impact.',
      'Review internally and approve to Ready using the authorized action.',
      'Issue the approved revision to the active project client. Preview/print the client-safe document.',
      'Obtain client approval in the portal or record valid acceptance internally.',
    ],
    next: 'Issuing preserves a snapshot; financial changes wait for acceptance.',
    notes: [
      'Negative costs/fixed markup can represent credits while quantities stay nonnegative. Schedule impact records the agreed number of days; it does not automatically reschedule all tasks.',
    ],
  }),
  guide('changes', {
    id: 'change-approval',
    extra: [
      {
        heading: 'Client price display',
        paragraphs: [
          'Client View shows the recorded final total by default. Project Client View settings can show subtotal and HST separately. This never changes the approved amount. Recorded portal decisions preserve the tax display reviewed by the client.',
        ],
      },
    ],
    title: 'Client approval and Change Order budget impact',
    summary:
      'Acceptance applies the client price and internal cost exactly once to their separate totals.',
    when: 'An issued Change Order has been approved.',
    destination: 'projects',
    related: ['change-orders', 'contract-summary', 'job-cost'],
    steps: [
      'Confirm the issued revision and named client. The authorized client can approve it in their portal with the requested acknowledgement.',
      'If recording acceptance internally, use the authorized action and enter the client name and evidence/reference.',
      'Verify the project has an original contract baseline and one active original/current budget; resolve missing baselines rather than inventing them.',
      'After acceptance check Current Contract and the new Change Order budget version.',
    ],
    next: 'Pre-tax client price adjusts Current Contract; internal expected cost adjusts Current Budget. Original values stay preserved.',
    notes: [
      'Retries cannot apply the same acceptance twice. Decline/rejection does not change the ledger. Signed credits cannot make the resulting current contract or cost allocation negative.',
    ],
    kind: 'financial',
  }),
  guide('changes', {
    id: 'change-revisions',
    title: 'Change Order revisions, rejection and credits',
    summary: 'Keep the client’s approved history intact when the proposed change evolves.',
    when: 'An unaccepted issued change needs new wording/pricing, or an accepted change needs a later correction.',
    destination: 'projects',
    related: ['change-orders', 'change-approval'],
    steps: [
      'For eligible Ready, Issued or Rejected revisions, create a new draft revision and review its copied content.',
      'Reapprove and issue the new revision. The old superseded revision can no longer be accepted.',
      'Use a reasoned Reject or Void action where valid; those actions do not apply financial effects.',
      'For an already accepted change, create a separate corrective Change Order or credit.',
    ],
    next: 'Issued snapshots remain reproducible even when contacts or project details change.',
    notes: ['Accepted revisions cannot be silently edited, revised, voided or accepted again.'],
    kind: 'locked',
  }),
];
