import { guide } from './types';
export const operationGuides = [
  guide('schedule', {
    id: 'schedule-tasks',
    title: 'Schedule tasks, milestones and assignments',
    summary: 'Plan project work with dates, responsibilities and visible status.',
    when: 'Building the schedule or reviewing the next two to three weeks.',
    destination: 'projects',
    related: ['schedule-templates', 'schedule-adjustments', 'client-publishing', 'trade-schedule'],
    steps: [
      'Open Project → Schedule. Add a task or use a Schedule Template.',
      'Enter title, internal description, start/end dates, status and ordering. Flag a milestone for a key checkpoint.',
      'Assign internal users or relevant project contacts. Add predecessor links and lag where needed.',
      'Filter the list to focus on the relevant work. Use Edit for dates, assignments, descriptions and dependency details.',
      'Publish client wording through Clients or release trade wording through Trades only when ready.',
    ],
    next: 'Dates and assignments support task follow-up; published/assigned external views remain separately controlled.',
    notes: [
      'Schedule tasks are not the reusable Tasks used by the time clock. Dependencies express relationships and prevent cycles, but do not automatically move project dates.',
    ],
  }),
  guide('schedule', {
    id: 'schedule-adjustments',
    title: 'Timeline, inline status and bulk date shifts',
    summary: 'Make everyday schedule changes without opening each full task editor.',
    when: 'Updating progress or moving a selected group of tasks.',
    destination: 'projects',
    related: ['schedule-tasks', 'schedule-templates'],
    steps: [
      'Open the project Schedule and inspect its list and timeline.',
      'Use the inline status control for a simple progress change.',
      'Select only the tasks that should move. Enter the deliberate day shift or bulk status and apply it.',
      'Review resulting dates and dependencies, including related tasks you did not select.',
      'Use task Edit for an individual date correction and communicate changes to affected people.',
    ],
    next: 'Only selected records change; their existing dependency links remain.',
    notes: [
      'There is no editable calendar, drag-to-reschedule, critical-path or automatic cascading engine. Relative templates and shifts use calendar days, including weekends.',
    ],
  }),
  guide('selections', {
    id: 'estimate-allowances',
    title: 'Allowances already included in the contract',
    summary:
      'An allowance is included client value for a decision still to be made, with a separate internal cost baseline.',
    when: 'Setting up decisions after the proposal is accepted.',
    destination: 'projects',
    related: ['selection-options', 'selection-decisions', 'estimate-flags'],
    steps: [
      'Open Project → Selections and use the accepted-estimate allowance action to create source-linked allowances and selections.',
      'Alternatively record the actual contractual allowance using the allowance form, including classification, tax treatment and included internal cost.',
      'Link the allowance to its one selection. Split a contractual category into deliberate sub-allowances before publishing if you need separate decisions.',
      'Check the client allowance value before offering options.',
    ],
    next: 'The decision compares selected selling price with the included allowance; it does not charge the full amount again.',
    notes: [
      'Only accepted source estimate allowance lines establish contractual values through conversion. Repeating conversion does not recreate the same source allowance. An allowance is not an extra budget or second ledger.',
    ],
  }),
  guide('selections', {
    id: 'selection-options',
    title: 'Create options and publish a Selection',
    summary: 'Prepare a clear client decision with a deadline and reviewed prices.',
    when: 'A client must choose a product, finish or scope option.',
    destination: 'projects',
    related: ['selection-templates', 'selection-decisions', 'client-publishing', 'specifications'],
    steps: [
      'Open Project → Selections. Create a draft or use a selection template. Set title, category, client instructions, deadline and required status.',
      'Link the allowance where one is included. Add options with product details, quantity/unit, classification, internal cost, markup and client description.',
      'Add only client-safe existing photos/specification files to options; keep supplier quotes with private cost internal.',
      'Check client prices and allowance differences. Use Project → Clients preview to review the published client experience.',
      'Publish the selection when its wording, options and pricing are ready.',
    ],
    next: 'Authorized clients see the decision and can confirm one option. Due and overdue labels use the deadline.',
    notes: [
      'Options cannot be changed while published. An undecided selection can return to draft for editing; a decided one cannot be unpublished to erase evidence. Automated deadline reminders and supplier ordering are not implemented.',
    ],
    kind: 'client',
  }),
  guide('selections', {
    id: 'selection-decisions',
    title: 'Selection decisions, upgrades and credits',
    summary:
      'A confirmed option records an immutable decision and routes any price difference into a draft Change Order.',
    when: 'Following up after a client makes a selection.',
    destination: 'projects',
    related: ['change-orders', 'change-approval', 'estimate-allowances'],
    steps: [
      'Open the selection and read the confirmed option, client comment and financial difference.',
      'For zero price difference, check the Approved state; no contract/budget entry is created by that decision.',
      'For a nonzero difference, open the linked draft Change Order and review both the client adjustment and internal cost change.',
      'Follow the normal internal review, issue and client acceptance workflow.',
      'After the linked Change Order is accepted, check selection approval and close the completed selection where appropriate.',
    ],
    next: 'Contract/budget changes occur on Change Order acceptance, not on the initial choice.',
    extra: [
      {
        heading: 'Allowance differences',
        paragraphs: [
          '$12,000 included and $14,500 selected means +$2,500 before applicable tax. $12,000 included and $10,000 selected means a −$2,000 credit. Without an allowance, a $5,000 option represents +$5,000 additional scope.',
        ],
        kind: 'financial',
      },
    ],
    notes: [
      'The internal cost adjustment is separate from the selling-price difference. Confirmed choices cannot simply be replaced; discuss a correction and use a separate controlled change.',
    ],
  }),
  guide('selections', {
    id: 'specifications',
    title: 'Specifications: information rather than a decision',
    summary: 'Keep product or construction wording that does not require a priced client choice.',
    when: 'Recording a fixed specification or providing approved information to the client.',
    destination: 'projects',
    related: ['selection-options', 'selection-templates'],
    steps: [
      'Open Specifications within Project → Selections, or start from a template.',
      'Enter the category, title and description and save privately.',
      'Review the wording and deliberately publish when suitable for clients.',
      'Edit with care and verify the client view after saving.',
    ],
    next: 'Clients see only explicitly published specification wording.',
    notes: [
      'A specification does not create an approval, budget change or immutable client decision. Use a Selection and Change Order for priced choices.',
    ],
  }),
  guide('clients', {
    id: 'client-access',
    title: 'Invite a Client and manage portal access',
    summary: 'Give a deliberately linked client account access to a specific project.',
    when: 'The project is ready for client participation or an invitation needs attention.',
    destination: 'projects',
    related: ['contacts', 'client-publishing', 'messages'],
    steps: [
      'Add or find the Client contact and associate it with the project in Project settings.',
      'Open Project → Clients. Choose the contact and use Invite.',
      'The client uses the secure setup email if a new account is needed. A compatible existing linked account receives this project’s access.',
      'Use resend for an outstanding invitation, revoke to remove project access, or reactivate deliberately when appropriate.',
      'Check the access state and ask the client to open their project chooser.',
    ],
    next: 'Only explicitly granted projects are available to that client.',
    notes: [
      'A CLIENT contact or project relationship alone is not a portal grant. An unrelated account with the same email is not silently merged; ask an administrator to resolve identity conflicts. Never email passwords.',
    ],
  }),
  guide('clients', {
    id: 'client-publishing',
    title: 'Publish content and preview the Client Portal',
    summary: 'Choose what the client sees rather than exposing the internal project automatically.',
    when: 'Releasing a schedule item, update, file or decision.',
    destination: 'projects',
    related: ['client-access', 'daily-logs', 'file-visibility', 'selection-options'],
    steps: [
      'Open Project → Clients and use the publishing controls.',
      'For schedule items, enter client-safe title/description and explicitly publish. Internal task text is not used as a fallback.',
      'For an update, write the separate client summary and publish the daily log.',
      'Mark appropriate files/photos CLIENT-visible. Publish selections/specifications through their own workflows; only issued/client-facing Change Orders appear.',
      'Open Client preview and inspect the result. Preview actions are disabled.',
    ],
    next: 'Authorized clients receive an allowlisted view, not the internal project screen.',
    notes: [
      'Clients cannot see internal cost, markup, margin, internal notes, private logs, vendor pricing or unrelated projects. Unpublishing cannot erase an already confirmed decision or approval.',
    ],
    kind: 'client',
  }),
  guide('trades', {
    id: 'trade-access',
    title: 'Add and invite a subcontractor or vendor',
    summary:
      'Use the existing Contact/Company directory and explicit project access for trade participation.',
    when: 'A subcontractor or supplier needs project information or issued work.',
    destination: 'projects',
    related: ['work-orders', 'trade-documents', 'trade-schedule', 'contacts'],
    steps: [
      'Create or find the Company and its individual trade contact. Set the appropriate Subtrade or Vendor type and project relationship.',
      'Open Project → Trades and invite the specific contact.',
      'Confirm the contact used on purchasing documents is the intended recipient. Sharing a company name does not grant access to another contact’s work.',
      'Resend setup mail if needed; revoke or reactivate the project grant deliberately.',
      'Review outstanding acknowledgements, instructions and deficiencies in the trade workspace.',
    ],
    next: 'The trade signs in to a separate portal and sees authorized records addressed or released to their identity.',
    notes: [
      'Project association is not portal access. Clients, trades and internal staff use separate identity boundaries. Trade access never exposes client prices, selections, private messages or other trades’ work.',
    ],
  }),
  guide('trades', {
    id: 'trade-schedule',
    title: 'Share trade schedule and handle conflicts',
    summary: 'Expose relevant work while Cedar Winds retains control of master dates.',
    when: 'Coordinating site work with a specific subcontractor or supplier.',
    destination: 'projects',
    related: ['schedule-tasks', 'trade-access', 'site-instructions'],
    steps: [
      'Assign the task to the relevant Contact or use Project → Trades to deliberately release it to that contact.',
      'Provide trade-safe title/description rather than relying on internal scheduling notes.',
      'Ask the trade to review dates and submit Confirmed, Conflict or Question with their comment.',
      'Review the response in the internal trade workspace, resolve it and edit the actual schedule separately if required.',
    ],
    next: 'The response is recorded and staff are notified; task dates do not change from a trade response.',
    notes: [
      'Trade visibility is separate from client publishing. Assignment/release does not expose every project task.',
    ],
  }),
  guide('trades', {
    id: 'trade-documents',
    title: 'Share drawings and review trade uploads',
    summary: 'Give the intended trade access to project documents and collect supporting evidence.',
    when: 'Sharing current drawings or receiving shop drawings, delivery records or completion photos.',
    destination: 'projects',
    related: ['file-visibility', 'site-instructions', 'deficiencies'],
    steps: [
      'Upload the document through the project file workflow with the correct category and revision/description where available.',
      'Use trade sharing controls to release the TRADE-visible file to the intended contact or attach it to their authorized issued work/instruction/deficiency.',
      'Check which recipient can access it. TRADE classification alone is not permission for every trade on the job.',
      'Review files submitted through the trade portal, their uploader/origin and related work record.',
    ],
    next: 'Protected downloads recheck project and record-level access.',
    notes: [
      'Production uploads currently require durable storage setup by the operator. The app does not offer drawing markup, BIM or a full transmittal/version-control system. Label revised drawings clearly.',
    ],
    kind: 'trade',
  }),
  guide('trades', {
    id: 'site-instructions',
    title: 'Issue a Site Instruction',
    summary: 'Record formal operational direction to named trade recipients.',
    when: 'A trade needs clear instructions tied to work, a task or supporting drawings.',
    destination: 'projects',
    related: ['trade-access', 'work-orders', 'messages'],
    steps: [
      'Open Project → Trades and create a draft Site Instruction with title, instruction text and recipients.',
      'Add related issued purchasing/schedule context and suitable shared attachments. Keep internal notes private.',
      'Review and issue with the required authority.',
      'Follow up on required acknowledgements and questions. Close the instruction when its purpose is complete.',
    ],
    next: 'Issued wording and recipients remain historical evidence; acknowledgements preserve what was received.',
    notes: [
      'Do not silently edit issued instructions. Use a replacement instruction for substantive changes. An instruction or trade comment does not automatically approve extra cost or revise a commitment.',
    ],
    kind: 'locked',
  }),
  guide('trades', {
    id: 'deficiencies',
    title: 'Assign, verify and close a Deficiency',
    summary:
      'Track a punch item from assignment through trade completion evidence and Cedar Winds verification.',
    when: 'A specific item needs correction before completion.',
    destination: 'projects',
    related: ['trade-documents', 'trade-access'],
    steps: [
      'In Project → Trades create the deficiency with clear title, location, priority, due date and trade-visible description.',
      'Assign the intended trade contact and share appropriate supporting photos/files.',
      'The trade reviews the item, may mark work in progress, uploads evidence and marks Ready for review.',
      'Inspect the completed work. Use the authorized verification/close action, or reopen with feedback if more work is needed.',
    ],
    next: 'The history retains updates and completion evidence. Staff see items ready for review.',
    notes: [
      'Trades cannot close their own deficiency. Only the assigned trade sees its item; other trades on the project do not receive it automatically.',
    ],
  }),
  guide('contacts', {
    id: 'contacts',
    title: 'Contacts, Companies and Project Contacts',
    summary: 'Maintain the people and businesses you work with independently of login accounts.',
    when: 'Adding clients, prospects, trades, vendors or design consultants.',
    destination: 'contacts',
    related: ['project-team', 'client-access', 'trade-access'],
    steps: [
      'Open Contacts and search by name/company before creating a duplicate. Use category filters to narrow the directory.',
      'Create or edit the Company for the business, then the individual Contact with their email, phone, address and appropriate types.',
      'Use Client/Prospect for customers and leads; Subtrade/Vendor for purchasing; Consultant, Architect, Engineer or Designer for professional relationships where offered.',
      'Associate contacts with a project and choose their project-specific role in Project settings.',
      'Deactivate outdated records rather than replacing the identity on historical issued documents.',
    ],
    next: 'The same contact can participate in project, purchasing and invitation workflows.',
    notes: [
      'Contact is an address-book identity; User is an authenticated account; Employee is employment information. Creating one is not automatic authorization for the others. Issued snapshots retain historical addresses and names.',
    ],
  }),
  guide('site-records', {
    id: 'files-photos',
    title: 'Upload, find and download Files and Photos',
    summary: 'Keep project documents and site images with their project record.',
    when: 'Adding drawings, specifications, inspections or progress photographs.',
    destination: 'projects',
    related: ['file-visibility', 'daily-logs', 'trade-documents'],
    steps: [
      'Open Project → Files or Photos and use Upload.',
      'Choose the file, category and visibility. Add description or caption so someone else can understand it.',
      'Review the uploaded entry; use the protected download or photo display to open it.',
      'For project templates with a folder structure, use the displayed folder checklist as an organization guide.',
    ],
    next: 'Authorized users can retrieve the file through the app; visibility and project checks still apply at download time.',
    notes: [
      'Folders are currently a checklist, not actual directories. Production storage is deliberately unavailable until a durable adapter is configured. Do not assume a failed upload saved the bytes.',
    ],
  }),
  guide('site-records', {
    id: 'file-visibility',
    title: 'INTERNAL, CLIENT and TRADE file visibility',
    summary: 'Visibility is a sharing decision, not just a label.',
    when: 'Uploading or publishing a file, photo or attachment.',
    destination: 'projects',
    related: ['client-publishing', 'trade-documents'],
    steps: [
      'Use INTERNAL for staff-only content, including supplier quotes or documents with private cost.',
      'Use CLIENT only for content suitable for authorized clients of that project.',
      'Use TRADE for trade-suitable material, then explicitly share/attach it to the authorized trade record or recipient.',
      'Check attachments independently before publishing a selection, instruction or purchasing document.',
    ],
    next: 'The file route checks identity, project access and required record/visibility scope on every download.',
    notes: [
      'Knowing a file link does not grant access. A client-facing brochure and an internal supplier quote may concern the same product but need different visibility.',
    ],
    kind: 'important',
  }),
  guide('site-records', {
    id: 'daily-logs',
    title: 'Daily Logs and client Project Updates',
    summary:
      'Keep a dated record of site progress without publishing internal detail unintentionally.',
    when: 'Recording the day’s work, deliveries, conditions, inspections or issues.',
    destination: 'projects',
    related: ['client-publishing', 'files-photos', 'scope-templates'],
    steps: [
      'Open Project → Daily logs and create an entry for the correct date.',
      'Record work completed, conditions/weather, manpower, delays/issues, deliveries, visitors, inspections and general notes as relevant. Use standard wording only as a starting point.',
      'Associate appropriate existing attachments/photos where offered.',
      'For a client update, open Clients publishing controls and write a separate client-safe summary. Explicitly publish it.',
      'Use Client preview to check the update and its client-visible attachments.',
    ],
    next: 'Staff retain the detailed log; the client sees the published summary as a Project Update.',
    notes: [
      'Internal manpower, delays and general notes are not automatically exposed as the client update. Publishing a log does not turn every attached internal file into a client file.',
    ],
    kind: 'client',
  }),
  guide('communication', {
    id: 'notifications',
    title: 'Notifications and email',
    summary: 'Use your in-app inbox for recorded action notices.',
    when: 'A task, approval, decision, invitation or message needs attention.',
    destination: 'notifications',
    related: ['messages', 'my-work'],
    steps: [
      'Open Notifications and review unread entries.',
      'Follow an action link to its source record; verify the current state before acting.',
      'Use Mark read or Mark all read to organize your inbox.',
      'If an expected email is missing, check the in-app record and contact the office about email delivery.',
    ],
    next: 'Read state belongs to your account. Marking a notice read does not approve or complete its source record.',
    notes: [
      'In-app notices are authoritative; SMTP delivery is a separate configured service. Scheduled reminders are not yet a general background feature. Page reads do not create repeated event notifications.',
    ],
  }),
  guide('communication', {
    id: 'messages',
    title: 'Project messages and audience boundaries',
    summary: 'Keep client and trade discussions linked to project work.',
    when: 'An important decision or question should not remain only in text messages or email.',
    destination: 'projects',
    related: ['notifications', 'client-access', 'trade-access'],
    steps: [
      'Use Project → Messages for internal/client conversations, choosing the correct audience.',
      'For a trade conversation, use Project → Trades and choose the specific trade contact and optional related work, instruction or deficiency.',
      'Write a clear subject and message; use standard communication wording where offered and review it before sending.',
      'Read replies in the same thread. Use the formal selection/Change Order action when approval is required.',
    ],
    next: 'Participants can read only conversations they are authorized to access, and useful notices are generated.',
    notes: [
      'A message is not a Change Order acceptance or financial commitment. Client, internal and separate trades’ conversations are not automatically shared with each other.',
    ],
  }),
];
