import { guide } from './types';
export const quickbooksGuides = [
  guide('quickbooks', {
    id: 'qb-overview',
    title: 'QuickBooks Desktop: responsibilities and sync modes',
    summary:
      'CWManagement owns project operations; QuickBooks Desktop remains the accounting ledger.',
    when: 'Before configuring or operating the accounting connection.',
    destination: 'quickbooks',
    roles: ['OWNER', 'CONTROLLER'],
    related: ['qb-setup', 'qb-pilot', 'qb-mappings', 'qb-bills'],
    steps: [
      'Open Financials → QuickBooks and read the current mode and health.',
      'Use DISCOVERY for read queries and mapping. It creates no accounting transactions or project actuals.',
      'Use PILOT only for the explicitly allowlisted test records and reviewed Bill application.',
      'Use PAUSED to stop new financial writes/application while authentication and diagnostic reads remain available.',
      'Use ACTIVE only after deliberate authorized activation and the required live evidence or recorded Owner override.',
    ],
    next: 'Queued work is processed only when the Web Connector calls and current mode/source checks permit it.',
    notes: [
      'Software is implemented; Cedar Winds live QuickBooks validation remains pending. Automated tests are not live validation. PAUSED does not undo a write already delivered to QuickBooks. No QuickBooks Online, payroll, bank feeds or replacement general ledger is provided.',
    ],
    kind: 'financial',
  }),
  guide('quickbooks', {
    id: 'qb-setup',
    title: 'Set up Web Connector and bind the company',
    summary: 'Connect the accounting PC through outbound Web Connector requests.',
    when: 'Preparing the controlled first live connection with the Controller.',
    destination: 'quickbooks',
    related: ['qb-pilot', 'qb-mappings', 'qb-recovery'],
    steps: [
      'Back up the intended company file and use a suitable test/staging copy for the pilot. Have the authorized operator configure the connection in CWManagement.',
      'Download CWManagement.qwc. On the QuickBooks Desktop PC open Web Connector, add the QWC and authorize the correct company file.',
      'Enter the generated copy-once password in Web Connector. It is not inside the QWC and must not be shared in messages or screenshots.',
      'Run Update Selected on that PC. Return to CWManagement and inspect detected company name/path information.',
      'Explicitly bind CWManagement to the intended company, then run list discovery.',
    ],
    next: 'The dashboard records connector contact and observed identity. A different observed company stops financial sync.',
    notes: [
      'No inbound PC connection or port forwarding is needed. A company-name/path change requires investigation, not automatic rebinding. Password rotation invalidates the old password/tickets; enter the new password in Web Connector.',
    ],
  }),
  guide('quickbooks', {
    id: 'qb-mappings',
    title: 'Map Projects, Vendors, Employees and Cost Codes',
    summary: 'Link exact accounting identities rather than guessing by similar names.',
    when: 'Discovery has returned company lists and an eligible record needs synchronization.',
    destination: 'quickbooks',
    related: ['qb-pilot', 'qb-po', 'qb-time', 'legacy-codes'],
    steps: [
      'Refresh discovery lists and review active candidates.',
      'Map the CW Project to the correct QuickBooks Customer:Job. Map the vendor Contact or its reviewed Company to the Vendor.',
      'Map the internal employee account to the existing QuickBooks Employee; automatic employee creation is not supported.',
      'Map each financial Cost Code to the correct Item. Time requires a Service Item; eligible expense-line imports can use separate Account-to-Cost-Code mappings.',
      'Review unmapped, conflict, stale and disabled filters. Repair/confirm mappings deliberately before retrying blocked work.',
    ],
    next: 'Mapping enables a prerequisite; it does not itself queue or authorize a transaction.',
    notes: [
      'Outbound mappings need recent discovery. Existing accounting history restricts casual remapping/unlinking. Legacy CSV Accounting Codes are not automatically converted into QuickBooks Item mappings.',
    ],
  }),
  guide('quickbooks', {
    id: 'qb-pilot',
    title: 'Live Validation pre-flight and pilot allowlist',
    summary: 'Constrain the first accounting tests to reviewed identities and source records.',
    when: 'Preparing a live pilot or deciding whether it can be activated.',
    destination: 'quickbooks',
    related: ['qb-setup', 'qb-po', 'qb-time', 'qb-bills'],
    steps: [
      'In Live Validation, review secure application configuration, migration/connection state, company binding, queue health and unresolved issues.',
      'While in Discovery or Paused, save one Project, Vendor Contact, Employee, selected Cost Codes, one issued PO revision and selected approved time segments. Record the reason and backup confirmation.',
      'Check mappings/pre-flight and explicitly enable Pilot. Mappings alone cannot authorize unrelated production records.',
      'Perform PO, time, Bill, modified Bill, duplicate/retry and failure-recovery tests in that order. Record actual result, versions, record IDs and evidence for each.',
      'Promote only after reviewing all exit criteria. Record an explicit activation reason; an Owner override is not a claim of live validation.',
    ],
    next: 'Observed transaction evidence and human validation results appear separately in the live panel.',
    notes: [
      'Changing pilot scope invalidates old scope-specific evidence for promotion. A later failed result clears live-validation status and pauses an active connection. Never enter passwords in evidence notes.',
    ],
  }),
  guide('quickbooks', {
    id: 'qb-po',
    title: 'Preview and queue a Purchase Order for QuickBooks',
    summary: 'Send an eligible issued PO with its mapped Vendor, Job and Items.',
    when: 'The Controller is ready for the pilot PO or an authorized active export.',
    destination: 'quickbooks',
    related: ['purchase-orders', 'qb-mappings', 'qb-recovery'],
    steps: [
      'Choose the current issued PO revision in Queue approved records. Confirm the Project, Vendor and every required Item mapping.',
      'Use Preview QuickBooks Request. Inspect mapped references, quantities, rates, dates and totals; read any blocker before continuing.',
      'Queue the eligible record. Run Update Selected in Web Connector on the accounting PC or wait for Auto-Run.',
      'Inspect the returned status, TxnID, EditSequence and timestamp. Locate the PO in Desktop using its reference number and full CW number/revision in Memo.',
      'For a later revision, refresh the QuickBooks PO for review, compare changes and explicitly authorize the reviewed modification.',
    ],
    next: 'The existing accounting transaction is mapped to the CW issued history; retry protection avoids an uncontrolled second Add.',
    notes: [
      'Any taxable line or nonzero tax blocks export: Canadian purchase-tax handling is not live validated. Do not make a taxable PO tax-free to bypass this. Work Orders remain CW-only. Independently edited QuickBooks POs and synchronized cancellations need accounting review.',
    ],
    kind: 'financial',
  }),
  guide('quickbooks', {
    id: 'qb-time',
    title: 'Queue approved Time for QuickBooks',
    summary: 'Export approved project time without sending wages or creating duplicate entries.',
    when: 'Testing one eligible approved segment or exporting approved mapped time.',
    destination: 'quickbooks',
    related: ['approve-time', 'time-export', 'qb-mappings', 'qb-recovery'],
    steps: [
      'Confirm the segment is closed and approved for its current version.',
      'Check Employee, Project/Job and Service Item mappings, plus Pilot eligibility where applicable.',
      'Preview the intended employee, date, project, item and duration, then queue.',
      'Run Web Connector and inspect the returned transaction identifier and successful status.',
      'If synchronized time is later corrected, review the conflict with the Controller instead of queueing another Add.',
    ],
    next: 'The source version and returned accounting identity are recorded. Duration rounds once to the nearest minute.',
    notes: [
      'No wage, payroll or labour-burden calculation is sent. There is no automatic corrected-time modification. Coordinate with CSV accounting exports to avoid duplicate downstream entry.',
    ],
  }),
  guide('quickbooks', {
    id: 'qb-bills',
    title: 'Review and import a QuickBooks Bill',
    summary:
      'Turn correctly mapped Bill lines into project Actual Costs and, where matched, commitment consumption.',
    when: 'Running the first small test Bill or resolving staged accounting costs.',
    destination: 'quickbooks',
    related: ['qb-reconciliation', 'qb-modified-bills', 'commitment-fulfillment'],
    steps: [
      'Set an explicit historical import start date; do not pull years of accounting history by default. Queue/read Bills through Web Connector.',
      'In Bill review inspect reference, date, Vendor, each line amount/description and its Project/Cost Code allocation.',
      'Resolve missing Job/Item/Account mappings or explicitly allocate/ignore known non-project lines with a reason.',
      'Review the proposed commitment match. Use reliable linked PO evidence or a deliberate line choice, not a guess from amount/vendor.',
      'Preview the whole Bill. In Pilot, use Apply reviewed Bill with the exact preview and a reason; a changed source/allocation requires another preview.',
    ],
    next: 'Application creates normalized ActualCosts and consumes linked commitments atomically. Repeated versions do not create duplicates.',
    notes: [
      'Unmapped or unsupported Bills stay in review. A $25,000 commitment with a linked $10,000 actual leaves $15,000 remaining, not $35,000 exposure. Overages must be resolved by an issued purchasing revision.',
    ],
    kind: 'financial',
  }),
  guide('quickbooks', {
    id: 'qb-modified-bills',
    title: 'Modified, voided or deleted Bills and holds',
    summary:
      'Keep imported cost history accurate without deleting evidence or silently reimporting reversed costs.',
    when: 'The Controller changes or deletes an already imported Bill in Desktop.',
    destination: 'quickbooks',
    related: ['qb-bills', 'qb-reconciliation'],
    steps: [
      'For a returned modified Bill, review the previous/new amounts and exact source version. Preview and apply where required.',
      'Verify that the old active costs were reversed and the new amounts/consumption applied, rather than added on top.',
      'For a confirmed deletion or void not reliably returned by the query, use Reverse imported Bill / hold non-project Bill with a reason naming the evidence.',
      'Use Restore to review only after accounting-side verification, then explicitly preview/apply again.',
    ],
    next: 'Reconciliation preserves original rows/audit history and restores/reapplies consumption in one transaction. A hold prevents automatic reimport.',
    notes: [
      'Missing from a normal query never proves deletion. Automated deleted-Bill polling is not implemented. Zero outstanding balance may mean paid, not zero cost. Holding in CWManagement does not delete the QuickBooks Bill.',
    ],
    kind: 'financial',
  }),
  guide('quickbooks', {
    id: 'qb-reconciliation',
    title: 'Resolve unmapped or unsupported accounting costs',
    summary: 'Use reasoned operator decisions when automatic normalization is unsafe.',
    when: 'A Bill is in Review, Review required or Unreconciled.',
    destination: 'quickbooks',
    related: ['qb-bills', 'qb-modified-bills', 'qb-recovery'],
    steps: [
      'Read the line’s safe reference, date, amount, description and reason.',
      'Fix Job/Item/Account/Vendor mappings, or select a deliberate Project/Cost Code allocation. Cost Type follows the chosen classification.',
      'Select the matching commitment or explicitly unlink an incorrect match with a reason. Ignore only verified non-project cost.',
      'Preview and apply the reviewed version. A source change clears old line decisions and requires fresh review.',
      'Use a hold for verified unsupported/non-project situations and record the decision; a resolution note alone does not alter financial totals.',
    ],
    next: 'The reviewed ledger effect appears in Budget/job cost, with separate audit history.',
    notes: [
      'Grouped, tax-inclusive, foreign-currency and negative Bills cannot be safely guessed into ordinary project lines. Cheques, card charges, Vendor Credits and payroll imports are not enabled. Generic manual-actual controls cannot bypass these accounting rules.',
    ],
  }),
  guide('quickbooks', {
    id: 'qb-recovery',
    title: 'Queue status, errors, run diagnostics and safe retry',
    summary: 'Find out what happened before retrying an accounting operation.',
    when: 'Web Connector is overdue, a job failed, or a response was lost.',
    destination: 'quickbooks',
    related: ['qb-mappings', 'qb-pilot', 'qb-modified-bills'],
    steps: [
      'Read connection mode/health and last contact. Configuration alone does not mean the PC is connected.',
      'Inspect the run for company, mode, request type, source record, status code and human-readable result.',
      'For BLOCKED, repair prerequisites such as mappings or unsupported tax. For FAILED, review the accounting rejection and fix its cause before retrying.',
      'For RECONCILIATION_REQUIRED after an uncertain write, locate the actual Desktop transaction. Close the old run and use Verify uncertain transaction with the exact TxnID where supported; never resend blindly.',
      'For COMPANY_MISMATCH, stop financial work and restore/verify the intended company identity before explicit reconfirmation.',
    ],
    next: 'Bounded retries and explicit reconciliation preserve the transaction’s identity across outages.',
    notes: [
      'Record locks may receive limited retry; permission and stale EditSequence failures need operator action. Safe diagnostics can be copied to support, but never include passwords, tickets, raw authentication bodies or confidential accounting payloads.',
    ],
  }),
];
