import { guide } from './types';
export const templateGuides = [
  guide('templates', {
    id: 'template-library',
    title: 'Choosing the right company standard',
    summary:
      'Templates is the reusable company library. Choose the kind of standard that matches the work you want to repeat.',
    when: 'You want to avoid starting a common job from a blank form.',
    destination: 'templates',
    related: [
      'project-templates',
      'estimate-templates',
      'schedule-templates',
      'selection-templates',
      'proposal-templates',
      'scope-templates',
      'assemblies',
      'cost-catalog',
      'save-template',
    ],
    steps: [
      'Open Templates and choose the appropriate category. Search existing standards before creating another.',
      'Use Project Templates for bundles; Estimate Templates for priced sections/lines; Schedule Templates for relative tasks; Specs & Selections for decisions and information.',
      'Use Proposal Templates for proposal wording, Scope Templates for purchasing scope/terms, Assemblies for quantity-scaled components, and Cost Catalog for individual standard items.',
      'Use Daily Log and Communication templates for repeatable wording. Create or edit a standard, review all values and save.',
      'Archive standards that should no longer be offered for new work.',
    ],
    next: 'Saved standards are available through the corresponding project editor or setup wizard.',
    notes: [
      'No sample Cedar Winds costs or legal language are supplied. Use approved company information. Saving a template does not create a financial transaction or publish anything to a portal.',
    ],
  }),
  guide('templates', {
    id: 'project-templates',
    title: 'Creating and using Project Templates',
    summary:
      'A Project Template bundles reviewed company standards into a new project starting point.',
    when: 'You repeatedly build similar project types, such as cottages or renovations.',
    destination: 'templates',
    related: ['create-project', 'template-library', 'save-template'],
    steps: [
      'First create the estimate, schedule, selection and wording standards you want to reuse.',
      'In Templates choose Project Templates and create a named standard. Include the saved company standards you need.',
      'Set the stage, folder checklist, defaults and required team roles as appropriate. Keep schedule task keys unique across the bundle.',
      'Save, then choose this template in the New project wizard and assign the actual team members.',
      'Inspect the new project’s draft estimate, dated tasks, private selections/specifications and default wording.',
    ],
    next: 'The project stores the source version and copied content. Editing the company template later does not change that project.',
    notes: [
      'Bundled references are copied when the bundle is saved. Editing a component standard does not silently update an already saved bundle. Folder names are a setup checklist, not real storage folders. Reapplying a standard appends items; it does not merge or replace existing work.',
    ],
  }),
  guide('templates', {
    id: 'save-template',
    title: 'Saving project work as a Template',
    summary: 'Capture useful project structures, review them and turn them into company standards.',
    when: 'A schedule, estimate, selection sheet or proposal is worth reusing.',
    destination: 'projects',
    related: ['project-templates', 'copy-project', 'cost-catalog'],
    steps: [
      'Open the relevant project workspace and use Save as template. For a combined starting point use the project’s template tools.',
      'Name the standard so another employee understands its purpose.',
      'Review the captured structure in the template editor before saving. Remove names, addresses and job-specific promises from free text.',
      'Save to the library, then test it on an appropriate draft project before relying on it widely.',
    ],
    next: 'Later copies are independent. Archiving or editing the template does not rewrite earlier project records.',
    notes: [
      'Capture leaves out client identities, approvals, attachments, messages, time, commitments, actuals and accounting records. Free text still needs human review. Schedule capture supports one finish-to-start predecessor per task; unsupported graphs are blocked.',
    ],
  }),
  guide('templates', {
    id: 'estimate-templates',
    title: 'Estimate Templates and partial copying',
    summary: 'Reuse sections and priced lines without having to copy the entire standard.',
    when: 'Building an estimate from one or several company standards.',
    destination: 'templates',
    related: ['create-estimate', 'assemblies', 'catalog-import'],
    steps: [
      'In Templates choose Estimate Templates. Add named sections and lines with descriptions, classifications, units, quantities, costs, markup and tax flags.',
      'Use allowance/optional flags and client wording deliberately; section names organize the document while Cost Codes organize job costs.',
      'For CSV entry, download the template headings, preview your rows and fix errors before adding them to the editor and saving.',
      'Open a project’s editable Estimate and choose Use template. Select the required items or all items and apply.',
      'Repeat with another template if needed, then adjust quantities and pricing for the job.',
    ],
    next: 'Normal estimate lines are created and use the existing calculation and revision rules.',
    notes: [
      'Use a new estimate revision when the source is locked. Copying the same items again deliberately adds another set; it is not an update operation.',
    ],
  }),
  guide('templates', {
    id: 'schedule-templates',
    title: 'Schedule Templates: relative dates and dependencies',
    summary: 'Turn project start dates into a repeatable schedule framework.',
    when: 'A common sequence should be reused with new dates and team members.',
    destination: 'templates',
    related: ['schedule-tasks', 'schedule-adjustments', 'project-templates'],
    steps: [
      'Create a Schedule Template and give each task a unique key, title, phase and description.',
      'Enter its offset from project start and duration in days. Use zero duration for a milestone.',
      'For a dependent task, choose the predecessor key and lag. Its start is calculated from the predecessor’s finish plus lag, rather than its independent offset.',
      'Choose a default assignment role where useful. Project setup resolves the role to the assigned internal team member.',
      'Save and use the template with the new project’s start date. Inspect the resulting dates before releasing work.',
    ],
    next: 'Project tasks and dependency links are copied. Later edits to the template do not move project dates.',
    notes: [
      'These are calendar days, not a work-week engine. Template dependencies are finish-to-start with one predecessor; cycles, missing keys and duplicate keys are rejected. Tasks start private; client/trade publishing is separate.',
    ],
  }),
  guide('templates', {
    id: 'selection-templates',
    title: 'Specs & Selections Templates',
    summary: 'Reuse the decisions and specification wording a project commonly needs.',
    when: 'A similar project requires familiar finish or product decisions.',
    destination: 'templates',
    related: ['selection-options', 'specifications', 'estimate-allowances'],
    steps: [
      'Choose Specs & Selections in Templates. Add information-only specification items separately from selection decisions.',
      'For selections enter category, title, instructions, required status, deadline offset and available priced options.',
      'Review option classifications, quantities, costs and client wording. Save the standard.',
      'Use it in Project → Selections or include it in a Project Template.',
      'Review the private copies, link the actual contractual allowances and add client-safe files before publishing.',
    ],
    next: 'Copies become ordinary project records, using the normal decision and approval process.',
    notes: [
      'A selection template does not establish a contractual allowance on its own. Use the accepted estimate allowance conversion or record the actual included allowance. No client approval or attachments are copied.',
    ],
  }),
  guide('templates', {
    id: 'proposal-templates',
    title: 'Proposal wording templates',
    summary: 'Reuse introduction, scope, exclusions, assumptions and terms.',
    when: 'Preparing a proposal or saving approved company language.',
    destination: 'templates',
    related: ['create-proposal', 'save-template'],
    steps: [
      'Create a Proposal Template in Templates, or capture project proposal wording with Save as template.',
      'Enter only language suitable for reuse; have appropriate staff review commitments and terms.',
      'When creating a project proposal, use the wording picker or the project’s setup defaults.',
      'Review the populated text against the actual estimate and client before creating the snapshot.',
    ],
    next: 'The proposal combines reviewed wording with the chosen estimate and client information.',
    notes: [
      'The current template supports the existing wording fields, not an arbitrary legal-document or page-layout designer. No legal text is invented for Cedar Winds.',
    ],
  }),
  guide('templates', {
    id: 'scope-templates',
    title: 'Scope, Daily Log and Communication templates',
    summary: 'Reuse frequent wording while keeping every project entry deliberate.',
    when: 'Preparing recurring trade scope, site notes or a message.',
    destination: 'templates',
    related: ['work-orders', 'daily-logs', 'messages'],
    steps: [
      'Create a Scope, Daily Log or Communication standard in Templates. Give it a clear descriptive name.',
      'Use scope/terms wording in a draft PO or Work Order through the scope picker.',
      'Use the Daily Log wording picker or project setup default when writing a log.',
      'Use the communication wording picker in internal project messaging.',
      'Replace placeholders and check the recipient before saving or sending.',
    ],
    next: 'The text is copied into the current record and can be reviewed before the normal save/issue/send action.',
    notes: [
      'Scope templates do not automatically add priced PO lines. Applying wording is not an instruction to a trade until the normal issue or communication action is completed.',
    ],
  }),
  guide('catalog', {
    id: 'cost-catalog',
    title: 'Creating and maintaining Cost Catalog items',
    summary: 'Store a standard thing you often estimate, with its unit, cost and pricing defaults.',
    when: 'A repeated material or activity should be quick to add to estimates.',
    destination: 'templates',
    related: ['catalog-import', 'catalog-quick-add', 'assemblies', 'cost-codes'],
    steps: [
      'Open Templates → Cost catalog. Search before adding a new item.',
      'Enter its name, description, unit and standard unit cost. Select the Cost Code and Cost Type.',
      'Set markup method/value, taxable status and category. Use Source and Notes for pricing context and supplier reference where useful.',
      'Save. Search and edit an item when a confirmed company price changes; use Active to retire it.',
      'For a selected group, use the price-factor bulk action carefully and verify the resulting prices.',
    ],
    next: 'New estimate additions copy the catalog defaults. Existing project lines and assembly components do not reprice automatically.',
    notes: [
      'A Cost Code is a classification; a catalog item is a reusable priced item; an estimate line is the project-specific copy; an assembly is a group of components. The current catalog editor has no supplier-contact dropdown or supplier feed. Record useful supplier context in Source/Notes.',
    ],
    extra: [
      {
        heading: 'Price changes',
        paragraphs: [
          'A bulk factor of 1.05 raises selected standard costs by 5%. A version conflict stops the whole batch; refresh and review before trying again.',
        ],
        kind: 'financial',
      },
    ],
  }),
  guide('catalog', {
    id: 'catalog-import',
    title: 'Importing Cost Catalog CSV data',
    summary: 'Preview real company cost data before adding it to the library.',
    when: 'Moving a reviewed cost list into CWManagement.',
    destination: 'templates',
    related: ['cost-catalog', 'estimate-templates'],
    steps: [
      'Open Cost catalog → Import and download the provided headings.',
      'Use exact existing active Cost Code strings. Use LABOUR, MATERIAL, SUBCONTRACT, EQUIPMENT or OTHER for Cost Type.',
      'Use NONE, FIXED or PERCENT_ON_COST for markup, and true/false for taxable. Enter nonnegative numeric costs.',
      'Preview the file. Correct each reported row error before importing.',
      'Confirm the import and spot-check the resulting items and units.',
    ],
    next: 'Valid rows are added together; invalid imports do not partially populate the catalog.',
    notes: [
      'The limit is 500 rows and 100 KB. Imports create new items; they do not guess which old price to update by name. Avoid importing the same file twice.',
    ],
  }),
  guide('catalog', {
    id: 'catalog-quick-add',
    title: 'Add from Cost Catalog or save an estimate item',
    summary: 'Move between project-specific estimate lines and reusable company costs.',
    when: 'Adding standard work or preserving a useful custom item.',
    destination: 'projects',
    related: ['cost-catalog', 'create-estimate', 'assemblies'],
    steps: [
      'Open a draft/editable Estimate and choose Add from Cost Catalog. Search part of the item name.',
      'Select the standard item, then adjust its copied quantity, unit, cost or markup for this project and save the row.',
      'To reuse a good project line later, use its save-to-catalog action if you have catalog maintenance permission.',
      'Open the catalog to review the new entry and remove project-specific wording.',
    ],
    next: 'The estimate owns its own values; catalog edits cannot silently change an offer already being prepared or issued.',
    notes: [
      'Catalog access and catalog maintenance are separate permissions. Locked estimate revisions cannot receive new lines.',
    ],
  }),
  guide('catalog', {
    id: 'assemblies',
    title: 'Assemblies and quantity factors',
    summary: 'Add a repeatable group of estimate components by entering one base quantity.',
    when: 'Estimating a wall, deck or other repeated construction system.',
    destination: 'templates',
    related: ['estimate-templates', 'catalog-quick-add', 'estimate-pricing'],
    steps: [
      'In Templates choose Assemblies and add the individual component lines with cost classifications, units and costs.',
      'Set each component quantity as its factor per base unit. Give the assembly a name that states the base unit, such as per SF.',
      'In a project estimate choose Add assembly and enter the base quantity.',
      'Review each resulting line quantity and price, then adjust for project conditions.',
    ],
    next: 'The components become ordinary estimate lines; no purchase, budget or accounting transaction is created.',
    extra: [
      {
        heading: 'Worked example',
        paragraphs: [
          'For 2,400 SF, a factor of 1.0 creates 2,400 units; a factor of 0.5 creates 1,200 units. The line unit must agree with what the factor measures. Factors are simple multiplication, not a full formula language.',
        ],
        kind: 'tip',
      },
    ],
    notes: [
      'Quantities use four-place rounding. Assembly costs are stored values: catalog price changes do not automatically refresh them.',
    ],
  }),
];
