import { guide } from './types';
export const timeAdminGuides = [
  guide('time', {
    id: 'clock-in',
    title: 'Clocking in at the Shop or Office',
    summary: 'Start your workday with the Shop QR and the work mode assigned to you.',
    when: 'Beginning a paid workday.',
    destination: 'time',
    roles: ['FIELD', 'SHOP', 'SITE', 'OFFICE'],
    keywords: ['clock', 'punch', 'scan', 'hours'],
    related: ['site-travel', 'switch-clock-out', 'my-hours', 'clock-problems'],
    steps: [
      'Scan the active Shop QR and sign in with your own account if asked.',
      'Choose Shop or Office if more than one work mode is available. A single available mode is selected for you.',
      'Choose the approved project/cost centre. Shop also requires a task allowed for both you and that project; Office does not require a task.',
      'Add useful optional notes, then press CLOCK IN.',
      'Wait for the confirmed clocked-in state and check the displayed project and activity.',
    ],
    next: 'The app records your scan and effective paid start. A configured earliest paid start may be later than the actual scan.',
    notes: [
      'Opening the Time screen alone does not start time. If you scan at 6:43 with an earliest paid start of 7:00, both times are retained and paid time begins at 7:00.',
    ],
  }),
  guide('time', {
    id: 'site-travel',
    title: 'Site work: travel and Truck QR arrival',
    summary: 'Separate travel from productive site work using confirmed QR actions.',
    when: 'Leaving the shop for a jobsite or arriving at a new site.',
    destination: 'time',
    roles: ['FIELD', 'SITE'],
    keywords: ['clock', 'truck', 'travel', 'arrived'],
    related: ['clock-in', 'switch-clock-out', 'locate'],
    steps: [
      'Scan the Shop QR, select Site mode and the destination project, then CLOCK IN.',
      'The app starts a Travel segment toward that project. Do not assume site labour has started yet.',
      'At arrival, scan the Truck QR. Check the destination, choose the required task and add notes if useful.',
      'Press ARRIVED and wait for confirmation. Travel ends and site work begins.',
    ],
    next: 'The record separates travel hours from the selected site task and records the truck interaction.',
    notes: [
      'This is based on selections and QR scans, not GPS. An inactive or regenerated QR must be replaced by the current printed code.',
    ],
  }),
  guide('time', {
    id: 'switch-clock-out',
    title: 'Switch Projects or tasks and clock out',
    summary: 'Keep the current activity accurate as the day changes.',
    when: 'Changing work, moving between sites or finishing the day.',
    destination: 'time',
    roles: ['FIELD', 'SHOP', 'SITE', 'OFFICE'],
    keywords: ['clock', 'switch', 'out'],
    related: ['site-travel', 'my-hours', 'forgotten-shifts'],
    steps: [
      'Scan the appropriate Shop/Truck QR to view the current activity. Use SWITCH for a change.',
      'Select the new project/task and notes. At the Shop QR you may change between your allowed modes.',
      'For site work, a task-only change starts the new task immediately. A different site starts Travel; scan the Truck QR and press ARRIVED at the destination.',
      'At the end of the day press CLOCK OUT and confirm that the app no longer shows an active shift.',
    ],
    next: 'Confirmed switches close the previous segment and start the next at the same server time, avoiding gaps and overlaps.',
    notes: [
      'If connectivity drops, refresh to check whether the action was recorded before retrying. No offline punch queue exists.',
    ],
  }),
  guide('time', {
    id: 'my-hours',
    title: 'Current hours and My Hours',
    summary: 'Check your own recorded workday and last week’s approved hours.',
    when: 'Confirming a punch or reviewing your time.',
    destination: 'time',
    roles: ['FIELD', 'SHOP', 'SITE', 'OFFICE'],
    related: ['clock-in', 'approve-time'],
    steps: [
      'Tap the Cedar Winds / My hours button at the top left of the internal app.',
      'Review Today: scan/paid start where shown, current activity and total paid time.',
      'Review the previous week’s approved/pending summary and expand its breakdown.',
      'Tell your PM about an incorrect project, task or time rather than attempting a compensating punch.',
    ],
    next: 'PM-approved totals reflect reviewed records; the current day may still contain unapproved work.',
    notes: [
      'My Hours shows only your own records. It is not a pay statement and does not calculate wages, overtime or deductions.',
    ],
  }),
  guide('approval', {
    id: 'locate',
    title: 'Locate employees and trucks',
    summary:
      'See the last recorded operational state for people and trucks you are authorized to view.',
    when: 'Coordinating today’s work or checking an apparent open shift.',
    destination: 'locate',
    related: ['approve-time', 'forgotten-shifts', 'site-travel'],
    steps: [
      'Open Locate. Controllers subject to the clock-in rule must clock in first.',
      'Review employee mode, project, task and start time.',
      'Read truck location as inferred from recent QR interactions, not a live location sensor.',
      'Contact the employee or PM if the record does not match the known work.',
    ],
    next: 'New confirmed punches update the recorded state.',
    notes: ['PM scope depends on assigned employees and projects. No GPS tracking is used.'],
  }),
  guide('approval', {
    id: 'approve-time',
    title: 'Review and approve employee time',
    summary: 'Use Verify to check completed records before they enter final accounting exports.',
    when: 'Reviewing the previous completed week or correcting a questioned record.',
    destination: 'verify',
    roles: ['PM', 'PROJECT_MANAGER', 'OWNER'],
    keywords: ['clock', 'verify', 'approval', 'payroll'],
    related: ['forgotten-shifts', 'time-export', 'my-hours'],
    steps: [
      'Open Verify. Check the date range; the default is the previous Monday–Sunday week.',
      'Filter by employee, project, task, accounting code, status or work type as needed. Review each start/end, travel period and note.',
      'Correct authorized records with the correction action and reason. Confirm the project, task and suggested accounting code; normal labour needs a code before final approval.',
      'Select eligible closed lines, a day or the employee week and approve. Travel still needs review but is identified separately.',
      'Refresh after conflicts: approval checks the exact record version, so a changed record must be reviewed again.',
    ],
    next: 'Approved hours appear in the employee’s previous-week summary and become eligible for Send and the separately controlled QuickBooks path.',
    notes: [
      'Approval is not payroll calculation. Exported records are protected. Corrections to synchronized time need accounting reconciliation rather than a duplicate export.',
    ],
  }),
  guide('approval', {
    id: 'forgotten-shifts',
    title: 'Close a forgotten shift or correct a record',
    summary: 'Fix the actual record with an explanation instead of deleting history.',
    when: 'An employee forgot to clock out or recorded the wrong details.',
    destination: 'verify',
    related: ['approve-time', 'switch-clock-out'],
    steps: [
      'Confirm the actual work time with the employee or site lead.',
      'Use Verify’s forgotten-shift action for an open shift; enter the correct closing time and reason.',
      'For a closed editable record, use Correct and review employee/project/task, times, code and notes.',
      'Save, check for overlaps and re-review the resulting approval status.',
    ],
    next: 'The change is audited and the version changes. Invalid overlapping or stale updates are rejected.',
    notes: [
      'Use the displayed timezone carefully, especially around daylight-saving changes. Do not “fix” a forgotten shift by leaving tomorrow’s work unrecorded.',
    ],
  }),
  guide('approval', {
    id: 'time-export',
    title: 'Final accounting batches, CSV and email',
    summary: 'Create an immutable snapshot of approved time for the accounting process.',
    when: 'The completed period has been reviewed and is ready for accounting.',
    destination: 'send',
    roles: ['CONTROLLER', 'OWNER'],
    related: ['approve-time', 'legacy-codes', 'qb-time'],
    steps: [
      'Open Send after meeting any Controller clock-in requirement. Confirm period and employee/project filters.',
      'Select approved closed records. Check codes and travel totals before finalizing.',
      'Create the batch. Download the resulting CSV or send the report through the configured email action.',
      'Use Finalized exports to retrieve the saved snapshot rather than generating a duplicate batch.',
      'Only an Owner may use the explicit unapproved-record override, with a reason and careful review.',
    ],
    next: 'Finalized records are marked exported and the batch retains the submitted values.',
    notes: [
      'CSV and QuickBooks time are separate delivery paths. Coordinate with accounting to avoid entering the same hours twice in the accounting system. CWManagement does not calculate payroll, overtime, statutory pay, deductions or wages.',
    ],
  }),
  guide('reports', {
    id: 'reports',
    title: 'Where to find reports today',
    summary:
      'Use the implemented time and project reports; the top-level Reports area is still a placeholder.',
    when: 'You need hours, job-cost or operational summaries.',
    destination: 'projects',
    related: ['job-cost', 'time-export', 'locate', 'dashboard'],
    steps: [
      'Use Project → Budget for Cost Code/Cost Type job costing and budget history.',
      'Use Project → Time for scoped project hour information.',
      'Use Info for employee hour summaries by period, and Verify/Send for filterable time records and finalized CSV exports.',
      'Use Financials for purchasing/change queues and budget variance alerts where authorized.',
    ],
    next: 'Open the underlying record when a summary needs explanation.',
    notes: [
      'There is no general custom-report builder, full portfolio analytics or payroll engine. The top-level Leads screen is also a placeholder; use Contacts and project lifecycle fields for existing records.',
    ],
  }),
  guide('administration', {
    id: 'roles',
    title: 'Roles, capabilities and Project access',
    summary:
      'Your role supplies normal access, capabilities refine it, and assignments may limit which projects you can use.',
    when: 'Onboarding staff or diagnosing a missing action.',
    destination: 'admin',
    related: ['project-team', 'admin-people', 'client-access', 'trade-access'],
    steps: [
      'Ask an administrator to confirm the appropriate internal role and actual responsibilities.',
      'Review any explicit capability grants or denials and assigned projects.',
      'For time approval, also check the PM’s employee and project assignments.',
      'Grant only the needed access. Use separate external accounts and deliberate invitations for clients and trades.',
    ],
    next: 'The server checks access even if someone knows a screen or record URL.',
    extra: [
      {
        heading: 'Typical role direction',
        paragraphs: [
          'Owner has full internal authority. Controller focuses on accounting and reconciliation. Project Manager focuses on assigned project operations; approval/issue and margin rights are not automatically identical to the Owner’s.',
          'Estimator focuses on estimating/proposals and pricing. Designer and Office staff receive the applicable operational access. Field and Shop staff focus on their work/time, with additional capabilities only when deliberately granted.',
          'Client, Subtrade and Vendor are external portal identities, not internal employees with a reduced menu. Legacy PM, Site and Admin names may remain on existing accounts.',
        ],
      },
    ],
    notes: [
      'The manual is available to all internal users, but reading a guide does not grant the ability to perform it. Some action buttons may still appear before the server rejects an unauthorized action.',
    ],
  }),
  guide('administration', {
    id: 'admin-people',
    title: 'Employees, accounts and permissions',
    summary: 'Configure individual accounts, work modes and approved time choices.',
    when: 'Adding a new employee or changing their responsibilities.',
    destination: 'admin',
    related: ['roles', 'qr-codes', 'legacy-codes'],
    steps: [
      'Open Settings → Employees & permissions. Create or edit the employee’s name, email and active state.',
      'Set applicable roles/work modes, earliest paid start and optional timezone. A blank timezone inherits the company setting.',
      'Assign available projects/jobsites and tasks. A Shop/Site task must be allowed for the employee and the project.',
      'For PMs, configure both assigned employees and projects. Review capability overrides and project assignments.',
      'Save, reopen and use Send password setup / reset. Never enter or send a plaintext password as an account hash.',
    ],
    next: 'The employee sets their password through the secure email flow and sees their permitted work choices.',
    notes: [
      'Owner/Admin escalation is restricted. Deactivating a person preserves historical time. A literal “NULL” timezone is not blank; use a valid IANA timezone such as America/Toronto.',
    ],
  }),
  guide('administration', {
    id: 'cost-codes',
    title: 'Cost Codes and financial settings',
    summary:
      'Maintain the classification shared by estimates, budgets, purchasing and actual costs.',
    when: 'Adding reviewed Cedar Winds classifications or updating document defaults.',
    destination: 'financials',
    related: ['cost-catalog', 'legacy-codes', 'company-defaults', 'qb-mappings'],
    steps: [
      'Open Financials to add/edit Cost Codes or import the provided CSV format.',
      'Use the approved code string, name, type, hierarchy and active state; do not create competing codes casually.',
      'Open Financial settings for tax rate, document prefixes/counters and default terms.',
      'Review the impact on new documents; existing issued snapshots keep their recorded information.',
    ],
    next: 'Active codes become available for financial allocation. QuickBooks Item mappings still require deliberate setup.',
    notes: [
      'A Cost Code is not a catalog item or a schedule task. Do not assume legacy time Accounting Codes are automatically the same as financial Cost Codes.',
    ],
  }),
  guide('administration', {
    id: 'legacy-codes',
    title: 'Time Tasks, Accounting Codes and mappings',
    summary: 'Set the reusable time activities and legacy CSV classification suggestions.',
    when: 'Employees or PMs cannot choose the correct task/code.',
    destination: 'admin',
    related: ['approve-time', 'cost-codes', 'qb-mappings'],
    steps: [
      'Use Settings → Tasks to maintain active clocking activities; connect a default financial Cost Code where offered.',
      'Use Jobsites to allow the correct tasks for each project.',
      'Use Accounting codes to maintain the codes required by the existing time/CSV process.',
      'Use Code mappings for project+task, project-only or task-only suggestions. The more specific project+task mapping takes priority.',
      'Have the PM review suggested codes during approval.',
    ],
    next: 'Time entry choices and approval suggestions use the configured mappings.',
    notes: [
      'QuickBooks Item mapping is separate. Its approved-time path uses the segment Cost Code or task default, not an inferred legacy CSV mapping.',
    ],
  }),
  guide('administration', {
    id: 'qr-codes',
    title: 'Trucks and Shop/Truck QR codes',
    summary: 'Create printable scan entry points and retire compromised or outdated codes.',
    when: 'Onboarding a truck, replacing a poster or setting up time capture.',
    destination: 'admin',
    related: ['clock-in', 'site-travel'],
    steps: [
      'Create the active truck under Settings → Trucks.',
      'Open QR codes and create the Shop QR or the truck’s code with a clear label.',
      'Use Print and place the approved code at the intended location.',
      'Use Revoke or Regenerate deliberately when replacing a code, then replace all old prints.',
    ],
    next: 'Scans identify the shop/truck entry point and the signed-in employee’s current state.',
    notes: [
      'Regeneration invalidates the old printed QR immediately. QR codes do not bypass login or provide GPS.',
    ],
  }),
  guide('administration', {
    id: 'company-defaults',
    title: 'Company defaults, time settings and numbering',
    summary: 'Reduce repeated entry using reviewed company-wide defaults.',
    when: 'Company details, tax, markup or workday/report conventions need maintenance.',
    destination: 'admin',
    related: ['cost-codes', 'template-library', 'time-export'],
    steps: [
      'Open Settings → Time & report settings and review Company Defaults.',
      'Set province and default markup policy, then review the time/report settings including timezone and accounting email recipient.',
      'Use the Financial settings link for tax, numbering prefixes/counters and standard financial terms.',
      'Review branding/contact information where provided. Test new drafts after changing defaults.',
    ],
    next: 'New entries use configured defaults; existing issued snapshots remain unchanged.',
    notes: [
      'A schedule work-week engine and automatic selection-reminder scheduler are not implemented. Project numbers are entered in the project wizard; do not assume every number uses an automatic counter.',
    ],
  }),
  guide('administration', {
    id: 'admin-import-audit',
    title: 'Admin CSV imports, Audit log and site visits',
    summary: 'Import supported setup records safely and inspect recorded administrative changes.',
    when: 'Loading initial employee/task/code data or reviewing who changed something.',
    destination: 'admin',
    related: ['catalog-import', 'project-overview', 'reports'],
    steps: [
      'Open Settings → CSV import and download the format for the supported entity.',
      'Preview the actual data, correct row errors and confirm only after reviewing duplicates/validation results.',
      'Use Settings → Audit log to inspect recorded actions; project activity is the simpler project-scoped summary.',
      'Use Site visit to start/end an Owner-style project visit where authorized.',
    ],
    next: 'Imported setup records enter their normal workflows. Site visits are retained separately from employee payroll time.',
    notes: [
      'Do not import passwords or secrets in an ordinary company-data CSV. Site visit time does not automatically create a paid employee shift.',
    ],
  }),
];
